### ISSUE TITLE
Exception in thread "OkHttp Dispatcher" java.lang.NoSuchFieldError: instance

### ISSUE THREAD

**Issue by wenhai2000** [PlexPt/chatgpt-java#144]
**Exception in thread "OkHttp Dispatcher" java.lang.NoSuchFieldError: instance
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.java:77)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.java:56)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
**

**Comment by FizzX11** [comment]
解决了吗？我也遇到相同的问题

**Comment by FizzX11** [comment]
> 

解决了，webmvc版本的问题，里面引入的okhttp和这个包的sse依赖冲突，springboot版本选2.7.12就行，主要看mvc版本和作者的依赖的mvc版本对应上就可以

**Comment by PlexPt** [comment]
okhttp版本不对
