### ISSUE TITLE
报错：Remote host closed connection during handshake

### ISSUE THREAD

**Issue by AceXia** [PlexPt/chatgpt-java#156]
运行时报错如下：在网上看到要升级jdk版本，现在已经升级了jdk1.8.0_201，依然报错，各位大佬赐教一下
Exception in thread "main" java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Single.blockingGet(Single.java:2870)
	at com.plexpt.chatgpt.ChatGPT.chatCompletion(ChatGPT.java:148)
	at com.linko.ypzk.spider.imslp.chatGPT.Test.main(Test.java:40)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:994)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379).....

**Comment by PlexPt** [comment]
检查一下网络



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月20日(周二) 下午5:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PlexPt/chatgpt-java] 报错：Remote host closed connection during handshake (Issue #156)




 
运行时报错如下：在网上看到要升级jdk版本，现在已经升级了jdk1.8.0_201，依然报错，各位大佬赐教一下
 Exception in thread "main" java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
 at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
 at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
 at io.reactivex.Single.blockingGet(Single.java:2870)
 at com.plexpt.chatgpt.ChatGPT.chatCompletion(ChatGPT.java:148)
 at com.linko.ypzk.spider.imslp.chatGPT.Test.main(Test.java:40)
 Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
 at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:994)
 at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
 at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
 at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379).....
