### ISSUE TITLE
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "completion_tokens_details" (class com.plexpt.chatgpt.entity.billing.Usage), not marked as ignorable (3 known properties: "prompt_tokens", "completion_tokens", "total_tokens"])

### ISSUE THREAD

**Issue by 165149324** [PlexPt/chatgpt-java#320]
Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "completion_tokens_details" (class com.plexpt.chatgpt.entity.billing.Usage), not marked as ignorable (3 known properties: "prompt_tokens", "completion_tokens", "total_tokens"])
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 22, column: 35] (through reference chain: com.plexpt.chatgpt.entity.chat.ChatCompletionResponse["usage"]->com.plexpt.chatgpt.entity.billing.Usage["completion_tokens_details"])
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:90)

**Comment by OleksandrMiadelets** [comment]
I have the same issue

**Comment by PlexPt** [comment]
show your code

**Comment by wanggang1997** [comment]
api 更新了，我之前一直正确使用，现在也出现这个错误了：
java.lang.RuntimeException: API调用异常: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "completion_tokens_details" (class com.plexpt.chatgpt.entity.billing.Usage), not marked as ignorable (3 known properties: "prompt_tokens", "completion_tokens", "total_tokens"])
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 22, column: 35] (through reference chain: com.plexpt.chatgpt.entity.chat.ChatCompletionResponse["usage"]->com.plexpt.chatgpt.entity.billing.Usage["completion_tokens_details"])

**Comment by OleksandrMiadelets** [comment]
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "completion_tokens_details" (class com.plexpt.chatgpt.entity.billing.Usage), not marked as ignorable (3 known properties: "prompt_tokens", "completion_tokens", "total_tokens"])
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 22, column: 35] (through reference chain: com.plexpt.chatgpt.entity.chat.ChatCompletionResponse["usage"]->com.plexpt.chatgpt.entity.billing.Usage["completion_tokens_details"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:987) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1974) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1701) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1679) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:330) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2033) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1458) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:33) ~[converter-jackson-2.9.0.jar!/:?]
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23) ~[converter-jackson-2.9.0.jar!/:?]
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243) ~[retrofit-2.9.0.jar!/:?]
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:204) ~[retrofit-2.9.0.jar!/:?]
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46) ~[adapter-rxjava2-2.9.0.jar!/:?]
        at io.reactivex.Observable.subscribe(Observable.java:12284) ~[rxjava-2.2.21.jar!/:?]
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35) ~[adapter-rxjava2-2.9.0.jar!/:?]
        at io.reactivex.Observable.subscribe(Observable.java:12284) ~[rxjava-2.2.21.jar!/:?]
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35) ~[rxjava-2.2.21.jar!/:?]
        at io.reactivex.Single.subscribe(Single.java:3666) ~[rxjava-2.2.21.jar!/:?]
        at io.reactivex.Single.blockingGet(Single.java:2869) ~[rxjava-2.2.21.jar!/:?]
        ... 5 more

**Comment by OleksandrMiadelets** [comment]
Looks like ChatGPT started returning an extra field completion_tokens_details in entity Usage

**Comment by PlexPt** [comment]
updating

**Comment by PlexPt** [comment]
fixed

已修复， 5.1.1

**Comment by wanggang1997** [comment]
maven仓库多久更新呢？目前还获取不到

**Comment by PlexPt** [comment]
数小时延迟
