### ISSUE TITLE
ChatGPT.builder().apiKeyList函数存在空指针的问题

### ISSUE THREAD

**Issue by TihPct** [PlexPt/chatgpt-java#74]
代码详情
```
ChatGPT chatGPT = ChatGPT.builder()
 .apiKeyList(Arrays.asList("key1","ke2","key3"))
 .proxy(proxy)
```
报错详情
```
Exception in thread "main" java.lang.NullPointerException: apiKey is marked non-null but is null
	at com.plexpt.chatgpt.ChatGPT.<init>(ChatGPT.java:49)
	at com.plexpt.chatgpt.ChatGPT$ChatGPTBuilder.build(ChatGPT.java:48)
```

**Comment by PlexPt** [comment]
fixed
